---

- name: java playbook
  hosts: all
  become: true

  vars:
    jdk_url: http://download.oracle.com/otn-pub/java/jdk/8u112-b15/jdk-8u112-linux-x64.rpm
    jdk_rpm: jdk-8u112-linux-x64.rpm

  tasks:

  - name: get java rpm
    get_url:
      url: "{{ jdk_url }}"
      validate_certs: no
      headers: 'Cookie: oraclelicense=accept-securebackup-cookie'
      dest: /home/vagrant/installers/{{ jdk_rpm }}
      owner: vagrant
      group: vagrant
      mode: 0755
    become: true
    become_user: vagrant
    become_method: su

  - name: install jdk
    yum:
      name: /home/vagrant/installers/{{ jdk_rpm }}
      state: present
